import React from 'react';
import { Printer, Wrench } from 'lucide-react';
import { fmtINR } from '../lib/pricing';
import { isDiamondStone } from '../lib/designTaxonomy';
import styles from './SpecSheet.module.css';

// Build the maker's tech-pack object from the design params + estimate.
// Pure: the page persists the returned object as design.spec_sheet.
export function buildSpecSheet(params = {}, estimate = null) {
  const c = params.center || {};
  const stoneCt = Number(params.pricing?.stone_weight_ct) || 0;
  const metalG = Number(params.metal_weight_g) || 0;

  const centre = (!c.stone_type || c.stone_type === 'None')
    ? null
    : {
        type: c.stone_type,
        shape: c.shape || '',
        carat: c.carat || '',
        count: c.count || '',
        color: isDiamondStone(c.stone_type) ? (c.color || '') : '',
        clarity: isDiamondStone(c.stone_type) ? (c.clarity || '') : '',
      };

  const accents = (params.accents || [])
    .filter(a => a && a.stone_type && a.stone_type !== 'None')
    .map(a => ({
      type: a.stone_type, shape: a.shape || '', count: a.count || '', setting: a.setting || '',
    }));

  const named = (params.motifs || []).filter(m => m && m !== 'Custom');
  if ((params.motifs || []).includes('Custom') && params.motif_custom?.trim()) {
    named.push(params.motif_custom.trim());
  }

  return {
    piece_type: params.piece_type || '',
    earring_subtype: params.piece_type === 'Earrings' ? (params.earring_subtype || '') : '',
    style: params.style || '',
    metal_type: params.metal_type || '',
    purity: params.purity || '',
    finish: params.finish || '',
    hallmark: !!params.hallmark,
    net_metal_weight_g: metalG,
    // Gross ≈ metal + stones (1 carat ≈ 0.2 g). Estimated, for the karigar.
    gross_weight_g: Math.round((metalG + stoneCt * 0.2) * 100) / 100,
    centre_stone: centre,
    accent_stones: accents,
    dimensions: params.dimensions || {},
    motifs: named,
    occasion: params.occasion || '',
    target_wearer: params.target_wearer || '',
    notes: params.spec_notes || '',
    estimated_total: estimate?.total ?? null,
  };
}

// Open a clean, self-contained popup and print just the spec sheet — keeps
// the app's chrome out of the printout without fighting CSS scoping.
function printSpec(spec) {
  const dimLines = Object.entries(spec.dimensions || {})
    .filter(([, v]) => v)
    .map(([k, v]) => `${k.replace(/_/g, ' ')}: ${v}`)
    .join(' · ');
  const centre = spec.centre_stone
    ? `${[spec.centre_stone.count, spec.centre_stone.carat && spec.centre_stone.carat + ' ct',
        spec.centre_stone.shape, spec.centre_stone.type].filter(Boolean).join(' ')}${
        spec.centre_stone.color || spec.centre_stone.clarity
          ? ` (${[spec.centre_stone.color && 'colour ' + spec.centre_stone.color,
              spec.centre_stone.clarity && 'clarity ' + spec.centre_stone.clarity].filter(Boolean).join(', ')})`
          : ''}`
    : '—';
  const accents = spec.accent_stones.length
    ? spec.accent_stones.map(a => [a.count, a.shape, a.type, a.setting && '· ' + a.setting + ' set'].filter(Boolean).join(' ')).join('<br>')
    : '—';
  const rows = [
    ['Piece', [spec.earring_subtype, spec.piece_type].filter(Boolean).join(' ')],
    ['Style', spec.style || '—'],
    ['Metal', [spec.purity, spec.metal_type].filter(Boolean).join(' ') || '—'],
    ['Finish', spec.finish || '—'],
    ['Hallmark (BIS)', spec.hallmark ? 'Yes' : 'No'],
    ['Net metal weight', spec.net_metal_weight_g ? spec.net_metal_weight_g + ' g' : '—'],
    ['Est. gross weight', spec.gross_weight_g ? spec.gross_weight_g + ' g' : '—'],
    ['Centre stone', centre],
    ['Accent stones', accents],
    ['Dimensions', dimLines || '—'],
    ['Motifs', spec.motifs.length ? spec.motifs.join(', ') : '—'],
    ['Occasion', spec.occasion || '—'],
    ['Wearer', spec.target_wearer || '—'],
    ['Notes', spec.notes || '—'],
  ];
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Maker's Spec Sheet</title>
    <style>
      body{font-family:Georgia,'Times New Roman',serif;color:#1C140C;margin:32px;}
      h1{font-size:20px;margin:0 0 2px;}
      .sub{color:#8a7a68;font-size:12px;margin:0 0 18px;}
      table{width:100%;border-collapse:collapse;}
      td{padding:8px 10px;border-bottom:1px solid #e7ddd0;vertical-align:top;font-size:13px;}
      td.k{width:180px;color:#8a7a68;font-weight:bold;text-transform:uppercase;letter-spacing:.04em;font-size:11px;}
      .total{margin-top:18px;font-size:14px;}
    </style></head><body>
    <h1>Maker's Spec Sheet</h1>
    <p class="sub">Karigar tech pack — generated by Swarnix Design Studio</p>
    <table>${rows.map(([k, v]) => `<tr><td class="k">${k}</td><td>${v}</td></tr>`).join('')}</table>
    ${spec.estimated_total != null ? `<p class="total"><b>Estimated price:</b> ₹${Number(spec.estimated_total).toLocaleString('en-IN')} (estimate only)</p>` : ''}
    <script>window.onload=function(){window.print();}</script>
    </body></html>`;
  const w = window.open('', '_blank', 'width=720,height=900');
  if (!w) return;
  w.document.write(html);
  w.document.close();
}

export default function SpecSheet({ params, setParams, estimate }) {
  const spec = buildSpecSheet(params, estimate);

  const Item = ({ label, children }) => (
    <div className={styles.item}>
      <span className={styles.k}>{label}</span>
      <span className={styles.v}>{children || '—'}</span>
    </div>
  );

  const centreText = spec.centre_stone
    ? [
        spec.centre_stone.count, spec.centre_stone.carat && spec.centre_stone.carat + ' ct',
        spec.centre_stone.shape, spec.centre_stone.type,
        (spec.centre_stone.color || spec.centre_stone.clarity) &&
          `(${[spec.centre_stone.color && 'colour ' + spec.centre_stone.color,
               spec.centre_stone.clarity && 'clarity ' + spec.centre_stone.clarity].filter(Boolean).join(', ')})`,
      ].filter(Boolean).join(' ')
    : '';

  const dimText = Object.entries(spec.dimensions || {})
    .filter(([, v]) => v).map(([k, v]) => `${k.replace(/_/g, ' ')}: ${v}`).join(' · ');

  return (
    <div className={styles.panel}>
      <div className={styles.head}>
        <Wrench size={14} />
        <span>Maker's spec sheet</span>
        <button type="button" className={styles.printBtn} onClick={() => printSpec(spec)}>
          <Printer size={13} /> Print
        </button>
      </div>

      <div className={styles.grid}>
        <Item label="Piece">{[spec.earring_subtype, spec.piece_type].filter(Boolean).join(' ')}</Item>
        <Item label="Style">{spec.style}</Item>
        <Item label="Metal">{[spec.purity, spec.metal_type].filter(Boolean).join(' ')}</Item>
        <Item label="Finish">{spec.finish}</Item>
        <Item label="Hallmark (BIS)">{spec.hallmark ? 'Yes' : 'No'}</Item>
        <Item label="Net metal wt.">{spec.net_metal_weight_g ? spec.net_metal_weight_g + ' g' : ''}</Item>
        <Item label="Est. gross wt.">{spec.gross_weight_g ? spec.gross_weight_g + ' g' : ''}</Item>
        <Item label="Centre stone">{centreText}</Item>
        <Item label="Accent stones">
          {spec.accent_stones.length
            ? spec.accent_stones.map((a, i) => (
                <div key={i}>{[a.count, a.shape, a.type, a.setting && '· ' + a.setting + ' set'].filter(Boolean).join(' ')}</div>
              ))
            : ''}
        </Item>
        <Item label="Dimensions">{dimText}</Item>
        <Item label="Motifs">{spec.motifs.join(', ')}</Item>
        <Item label="Occasion">{spec.occasion}</Item>
        <Item label="Wearer">{spec.target_wearer}</Item>
      </div>

      <div className={styles.notesWrap}>
        <label className={styles.notesLabel}>Notes for the karigar</label>
        <textarea
          className={styles.notes}
          rows={3}
          value={params.spec_notes || ''}
          onChange={e => setParams(f => ({ ...f, spec_notes: e.target.value }))}
          placeholder="Soldering, stringing, clasp type, special instructions…"
        />
      </div>
    </div>
  );
}
